### PR TITLE
Make httplog work with newer httprb/http

### PR DESCRIPTION
**Pull request by mhenrixon**
Sending this to be able to get some feedback!

I have no idea if this is the best way of solving the problem but it does work for me locally.

### CODE REVIEW

**Comment by trusche** [comment]
Hi @mhenrixon, sorry for the delayed reply - I'm not ignoring this, just a bit busy atm. Will try to get around to it over the next couple of weeks. Would you mind taking a look at the failing specs in the meantime?

**Comment by mhenrixon** [comment]
I didn't even realise specs failed. The "Works on my machine™" syndrome. I'll get it done!

**Comment by trusche** [comment]
Thanks @mhenrixon for getting me started on this. I [refactored it a bit](https://github.com/trusche/httplog/commit/50020ae841c4feedefc7d9e8557803e0e79e0583) and tested with versions 0.8.4 and the latest 1.0.4 of `httprb`.

**Comment by trusche** [comment]
Released as `0.3.1`.

**Comment by mhenrixon** [comment]
Thanks @trusche, sorry I never got around to it. Been such a crazy time the last few weeks. Glad we got it sorted :

**Pull request merged**
