### PR TITLE
Mask secrets inside XML requests and responses

### PR DESCRIPTION
**Pull request by bustikiller**
### What

In some circumstances, secrets are sent inside XML request and responses instead of using HTTP headers. The traces of these requests need to mask the configured secrets to avoid the exposure of sensitive information. 

### How

- Wrap the masking of Strings using a method that transforms XMLs into hashes before masking, and back to Strings after masking is done.
- Using the `masked` method in the `parse_body` method.

### CODE REVIEW

**Comment by trusche** [comment]
Hiya @bustikiller, thanks for the PR, a wee bit busy right now so review might take a while.

**Comment by trusche** [comment]
I just took a quick peek - would you mind adding a spec or two that fail without these code changes and pass with them please? With a dedicated XML file?  It would also help me understand the use case better. 

Thanks!

**Comment by bustikiller** [comment]
Hi @trusche, 

The existing tests already fail just by adding some "sensitive information" nested inside the HTML response. I developed this feature in TDD mode, making sure that the sensitive information just added to the response was masked before logging. 

The use case I was thinking of is an API where credentials are not sent in headers but inside the payload.

I will try to find some time to add new test cases specific for this feature. 

Thanks!

**Comment by trusche** [comment]
Well, we can only mask sensitive values in structure data for well-known keys, etc. `password=foo` or `<password>foo</password>` in XML. The example has the value as part of a larger string, there's no telling what to actually mask. Unless I'm missing something. I'm also wary of how converting a big XML doc to text and back might impact performance. I'll take a closer look later.

**Comment by bustikiller** [comment]
Closing stale PR

**Pull request closed without merging**
