### PR TITLE
Fix method called on nil in the Ethon adapter when the response headers are empty

### PR DESCRIPTION
**Pull request by RKushnir**
Resolves https://github.com/trusche/httplog/issues/67

### CODE REVIEW

**Comment by trusche** [comment]
Heh, race condition. Please check out my commit on #67 and see if that works.

**Comment by RKushnir** [comment]
Yes, it works. Thanks for a very quick fix. 🙂 
I like my solution slightly better, because it doesn't do an array -> nil -> array conversion, but I'm happy as long as it works.

**Comment by trusche** [comment]
I agree!

**Comment by trusche** [comment]
1.2.1 released. Thanks again!

**Comment by RKushnir** [comment]
Thank you! That was fast! 🤝

**Pull request merged**
