### PR TITLE
Enable JSON logging

### PR DESCRIPTION
**Pull request by bustikiller**
This pull request adds the option to log HTTP requests as JSON.

**NOTE**: http4 does not support ruby < 2.3.X, so the build for that combination has been flagged as "allow_failure"

### CODE REVIEW

**Comment by trusche** [comment]
Hi @bustikiller, I'd be happy to accept this with existing specs passing and new specs added to cover the added behaviour. Currently it breaks compact logging. See for example https://travis-ci.org/trusche/httplog/jobs/450821360.

**Comment by bustikiller** [comment]
Hi @trusche, this is still work in progress, I will fix the existing tests and write new tests for the added feature. Thanks!

**Comment by trusche** [comment]
Cool, just assign to me when you consider it done.

**Comment by bustikiller** [comment]
@trusche did you have a chance to review this PR? I added a small change to identify `application/pdf` as binary, as it was causing some troubles with the transformation to JSON. It may be aligned with https://github.com/trusche/httplog/issues/61.

**Comment by trusche** [comment]
Hi @bustikiller, sorry I've been swamped. I'll try to get around to this this weekend.

**Comment by trusche** [comment]
Hi @bustikiller I've merged this into master and then added some refactorings on top. Would you let me know if master is working ok for you? I'm aiming to release this as 0.1.20 in a few days.

**Pull request merged**
