### PR TITLE
Fix response encoding

### PR DESCRIPTION
**Pull request by tycooon**
Currently, logger fails to log the response in case it has non-ascii characters (for example, cyrillics), with similar message to STDERR: `log writing failed. "\xD0" from ASCII-8BIT to UTF-8`. This patch tries to set the response encoding to the one that was passed in the HTTP-header, and if there is no such encoding, then it just assumes the response was UTF-8 which is true in most cases.
I'm not sure how to properly test this behavior in specs though.

P. S. To replicate the problem, just run something like this with httplog turned on: `HTTParty.get("http://ya.ru")`. You will see the message in STDERR.

### CODE REVIEW

**Comment by trusche** [comment]
Hi @tycooon 

Thanks for the PR, but I can't reproduce your issue:

```
irb -I./lib
irb(main):001:0> require 'httplog'
=> true
irb(main):002:0> require 'httparty'
=> true
irb(main):003:0> HTTParty.get("http://ya.ru")
D, [2016-01-14T14:33:26.920603 #2430] DEBUG -- : [httplog] Connecting: ya.ru:80
D, [2016-01-14T14:33:27.608251 #2430] DEBUG -- : [httplog] Sending: GET http://ya.ru:80/
D, [2016-01-14T14:33:27.608361 #2430] DEBUG -- : [httplog] Data:
D, [2016-01-14T14:33:27.693446 #2430] DEBUG -- : [httplog] Status: 302
D, [2016-01-14T14:33:27.693552 #2430] DEBUG -- : [httplog] Benchmark: 0.084977 seconds
D, [2016-01-14T14:33:27.693618 #2430] DEBUG -- : [httplog] Response:

D, [2016-01-14T14:33:27.709135 #2430] DEBUG -- : [httplog] Connecting: ya.ru:443
D, [2016-01-14T14:33:27.962054 #2430] DEBUG -- : [httplog] Sending: GET http://ya.ru:443/
D, [2016-01-14T14:33:27.962151 #2430] DEBUG -- : [httplog] Data:
D, [2016-01-14T14:33:28.065772 #2430] DEBUG -- : [httplog] Status: 200
D, [2016-01-14T14:33:28.065874 #2430] DEBUG -- : [httplog] Benchmark: 0.103535 seconds
D, [2016-01-14T14:33:28.066720 #2430] DEBUG -- : [httplog] Response:
<!DOCTYPE html><html class="i-ua_js_no i-ua_css_standart i-ua_browser_" lang="ru"><head xmlns:og="http://ogp.me/ns#"><meta http-equiv="X-UA-Compatible" content="IE=edge"><title>������������</title><meta http-equiv=Content-Type content=
...
```

However, I've pushed a change to master that move the encoding enforcement that already existed for data (request) logging to the generic log method so it's also applied to response data. Please try that version and let me know if it fixes your issue.

**Comment by tycooon** [comment]
Well, I cannot reproduce that in irb as well, but running in rails console it doesn't work. I guess that's because I have logging configured in an initializer like this: 

```ruby
HttpLog.options[:logger] = Logger.new(Rails.root.join('log/http_requests.log'))
```

Your recent commit fixed the main problem, but non-ascii symbols are still logged like some broken symbols (������������). In my version, the output is assumed utf-8 if no other encoding was provided by the http-client (which is still true in like 99% of cases) and therefore cyrillics and stuff get logged properly.

**Comment by trusche** [comment]
Hmm, ok. I'll take another close look in a Rails context. This might be what I need to fix this &*^*& encoding crap once and for all. Thanks, stay tuned!

**Comment by trusche** [comment]
For the life of me, I can't replicate this behavior in a test. But I am able to reproduce it from the  console when logging to a file instead of STDOUT or a StringIO. So. I've implemented your conversion method, please try this latest commit, and if that all works, that shall be good enough. :)

**Comment by tycooon** [comment]
Yes, it's seems to work, good job! 
Why can't you write into a file in your tests and then read the result file and check it's contents?

**Comment by trusche** [comment]
That's a very good question, I've been trying to do any which way; but either it does not raise the error at all, or it raises it in the spec regardless of the fix. I'm sure there's an automatic conversion going on somewhere that I'm missing.

Anyway, I substantially refactored the whole thing; there were another couple of bugs in there:

1) Most adapters didn't look at the headers at all, so `encoding` was nil to begin with in most cases
2) The code was incorrectly looking at the `Content-Encoding` header - but that's only for transfer encodings (e.g. `gzip`). For character encoding, we need to look at the optional `charset` part of the `Content-Type` header.

So those are fixed now, I just pushed another commit. Specs are passing and your sample works as well. I'm going to use this internally for a day or two to make sure there's no regression, then I will publish v0.3.0.

**Comment by tycooon** [comment]
Great job, i checked the last master and it seems to work allright, looking forward for the new version!

**Comment by trusche** [comment]
Published as 0.3.0. Thanks!

**Pull request closed without merging**
